# Generated by Django 6.1 on 2026-08-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='prefixe_matricule',
            field=models.CharField(blank=True, help_text="Ex: EMA pour 'Emmanuel'. Utilisé pour générer les matricules élèves automatiquement.", max_length=10),
        ),
    ]
