# Generated by Django 6.1 on 2026-08-10 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: 2025-2026', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_active', models.BooleanField(default=False, help_text='Une seule année active à la fois par école.')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annees_scolaires', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'ordering': ['-date_debut'],
                'constraints': [models.UniqueConstraint(fields=('ecole', 'nom'), name='annee_unique_par_ecole')],
            },
        ),
    ]
