# Generated by Django 6.1 on 2026-08-10 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: 6ème, Terminale', max_length=50)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Pour trier l'affichage")),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: 6ème A', max_length=50)),
                ('effectif_max', models.PositiveSmallIntegerField(default=50)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academique.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='tenants.school')),
                ('matieres', models.ManyToManyField(blank=True, related_name='classes', to='academique.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academique.niveau')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['niveau__ordre', 'nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='matiere',
            constraint=models.UniqueConstraint(fields=('ecole', 'nom'), name='matiere_unique_par_ecole'),
        ),
        migrations.AddConstraint(
            model_name='niveau',
            constraint=models.UniqueConstraint(fields=('ecole', 'nom'), name='niveau_unique_par_ecole'),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(fields=('ecole', 'annee_scolaire', 'nom'), name='classe_unique_par_annee'),
        ),
    ]
