# Generated by Django 6.1 on 2026-08-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0003_note_bulletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='bareme_note',
            field=models.PositiveSmallIntegerField(default=20, help_text='Note maximale utilisée pour ce niveau (10 ou 20 généralement)'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='cycle',
            field=models.CharField(choices=[('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée')], default='college', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='niveau',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='valeur_max',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5),
        ),
    ]
