# Generated by Django 6.1 on 2026-08-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0004_niveau_bareme_note_niveau_cycle_alter_niveau_ordre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='fichier_pdf',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='moyenne_generale',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='rang',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
