# Generated by Django 6.1 on 2026-08-09 14:16

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(help_text="Identifiant interne de l'élève, unique DANS cette école", max_length=30)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=150)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Photo')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('transfere', 'Transféré'), ('exclu', 'Exclu'), ('diplome', 'Diplômé / Sorti')], default='actif', max_length=20)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='RelationParentEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lien', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('tuteur', 'Tuteur légal'), ('autre', 'Autre')], max_length=10)),
                ('contact_principal', models.BooleanField(default=False, help_text='Coché = ce parent reçoit les SMS/emails en priorité pour cet élève')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.eleve')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.parent')),
            ],
            options={
                'verbose_name': 'Relation parent-élève',
                'verbose_name_plural': 'Relations parent-élève',
            },
        ),
        migrations.AddField(
            model_name='eleve',
            name='parents',
            field=models.ManyToManyField(related_name='enfants', through='eleves.RelationParentEleve', to='eleves.parent'),
        ),
        migrations.AddConstraint(
            model_name='relationparenteleve',
            constraint=models.UniqueConstraint(fields=('parent', 'eleve'), name='lien_parent_eleve_unique'),
        ),
        migrations.AddConstraint(
            model_name='eleve',
            constraint=models.UniqueConstraint(fields=('ecole', 'matricule'), name='matricule_unique_par_ecole'),
        ),
    ]
