# Generated by Django 6.1 on 2026-08-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
