# Generated by Django 6.1 on 2026-08-11 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0005_alter_bulletin_fichier_pdf_and_more'),
        ('eleves', '0002_alter_eleve_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('redoublant', 'Redoublant'), ('transfere', "Transféré en cours d'année")], default='en_cours', max_length=20)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academique.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='academique.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'constraints': [models.UniqueConstraint(fields=('eleve', 'annee_scolaire'), name='une_seule_classe_par_eleve_par_annee')],
            },
        ),
    ]
